- job_name: 'federate'
  scrape_interval: {{ .Values.clusterPrometheus.interval }}
  honor_labels: true
  metrics_path: '/federate'

  params:
    'match[]':
      - '{namespace=~"{{ .Values.global.cattle.projectNamespaces | join "|" }}", job=~"kube-state-metrics|kubelet"}'
      - '{namespace=~"{{ .Values.global.cattle.projectNamespaces | join "|" }}", job=""}'

  static_configs:
    - targets:
      - "{{ .Values.clusterPrometheus.host }}:{{ .Values.clusterPrometheus.port }}"
