apiVersion: v2
name: rancher-project-monitoring
description: Rancher Project Monitoring
version: 0.0.1
appVersion: 0.0.1
# icon: https://charts.rancher.io/assets/logos/rancher-project-monitoring.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/release-name: rancher-project-monitoring
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows