annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/operator: "true"
  catalog.cattle.io/auto-install: rancher-monitoring-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/deploys-on-os: windows
  catalog.cattle.io/display-name: Monitoring
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.28.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: monitoring.coreos.com.prometheus/v1
  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
  catalog.cattle.io/release-name: rancher-monitoring
  catalog.cattle.io/requests-cpu: 4500m
  catalog.cattle.io/requests-memory: 4000Mi
  catalog.cattle.io/type: cluster-tool
  catalog.cattle.io/ui-component: monitoring
  catalog.cattle.io/upstream-version: 45.31.1
apiVersion: v2
appVersion: v0.65.1
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: file://./charts/grafana
description: Collects several related Helm charts, Grafana dashboards, and Prometheus
  rules combined with documentation and scripts to provide easy to operate end-to-end
  Kubernetes cluster monitoring with Prometheus. Depends on the existence of a Cluster
  Prometheus deployed via Prometheus Operator
home: https://github.com/prometheus-operator/kube-prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- prometheus
- monitoring
maintainers:
- email: arvind.iyengar@suse.com
  name: Arvind
- email: amangeet.samra@suse.com
  name: Geet
  url: https://github.com/geethub97
name: rancher-project-monitoring
type: application
version: 0.4.1
