apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Job associated with updates to this chart
      jsonPath: .status.jobName
      name: Job
      type: string
    - description: Helm Chart name
      jsonPath: .spec.chart
      name: Chart
      type: string
    - description: Helm Chart target namespace
      jsonPath: .spec.targetNamespace
      name: Target Namespace
      type: string
    - description: Helm Chart version
      jsonPath: .spec.version
      name: Version
      type: string
    - description: Helm Chart repository URL
      jsonPath: .spec.repo
      name: Repo
      type: string
    - description: Helm version used to manage the selected chart
      jsonPath: .spec.helmVersion
      name: Helm Version
      type: string
    - description: True if this is chart is needed to bootstrap the cluste
      jsonPath: .spec.bootstrap
      name: Bootstrap
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              bootstrap:
                type: boolean
              chart:
                nullable: true
                type: string
              chartContent:
                nullable: true
                type: string
              failurePolicy:
                nullable: true
                type: string
              helmVersion:
                nullable: true
                type: string
              jobImage:
                nullable: true
                type: string
              repo:
                nullable: true
                type: string
              repoCA:
                nullable: true
                type: string
              set:
                additionalProperties:
                  nullable: true
                  type: string
                nullable: true
                type: object
              targetNamespace:
                nullable: true
                type: string
              timeout:
                nullable: true
                type: string
              valuesContent:
                nullable: true
                type: string
              version:
                nullable: true
                type: string
            type: object
          status:
            properties:
              jobName:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
