workingDir: ""
url: https://github.com/rancher/charts.git
subdirectory: charts/rancher-monitoring/103.0.2+up45.31.1
commit: 601e6b78a9c2d2aff99a314bc1c23c2b7d2cb10a
version: 0.4.1
ignoreDependencies:
  - hardenedKubelet
  - hardenedNodeExporter
  - k3sServer
  - kube-state-metrics
  - kubeAdmControllerManager
  - kubeAdmProxy
  - kubeAdmScheduler
  - kubeAdmEtcd
  - prometheus-adapter
  - prometheus-node-exporter
  - rke2ControllerManager
  - rke2Etcd
  - rke2IngressNginx
  - rke2Proxy
  - rke2Scheduler
  - rkeControllerManager
  - rkeEtcd
  - rkeIngressNginx
  - rkeProxy
  - rkeScheduler
  - windowsExporter
replacePaths:
  - README.md
  - app-README.md
